version: "3.7"
services:
    php:
        build:
            context: ../
            dockerfile: ./devops/php/Dockerfile-php
        volumes: 
            - ../project:/project
            - ../db:/db
        networks: 
            - zinio

networks: 
    zinio: