version: "3.7"
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes: 
            - ../project:/project
            - ../devops/site.conf:/etc/nginx/conf.d/default.conf
        links: 
            - php
        networks: 
            - zinio

    php:
        build:
            context: ../
            dockerfile: ./devops/php/Dockerfile-php
        volumes: 
            - ../project:/project
            - ../db:/db
        networks: 
            - zinio

networks: 
    zinio: